[project]
name = "dinasore-function-blocks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.14"
dependencies = [
    "numpy>=2.2.1",
]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]
